export const NEW_GAME_SUCCESS = 'NEW_GAME_SUCCESS';
export const MAKE_MOVE = 'MAKE_MOVE';
export const WIN_GAME_SUCCESS = 'WIN_GAME_SUCCES';
export const UPDATE_ON_CHANGE = 'UPDATE_ON_CHANGE';
export const GET_HIGH_SCORES_SUCCESS = 'GET_HIGH_SCORES_SUCCESS';
export const RESTART_BOARD = 'RESTART_BOARD';